export { default as Login } from "./Authenticate/Login";
export { default as Register } from "./Authenticate/Register";
export { default as HomePage } from "./HomePage";
export { default as Shop } from "./Shop";
export { default as Admin } from "./Admin";
export { default as DetailProduct } from "./DetailProduct";
export { default as ShopCart } from "./ShopCart";
export { default as Order } from "./Order";
export { default as VoucherPage } from "./Voucher";
